language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
addons:
  chrome: stable
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- ng build --prod --base-href https://github.com/Goku193/test-automation-workshops
- ng lint
- ng test
