language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
addons:
  chrome: stable
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- ng test --watch=false --browers=ChromeHeadless
- ng e2e
- ng build --prod --base-href https://Goku193.github.io/test-automation-workshops
